### PR TITLE
Abort Atomkraft CLI if run outside of a project

### LINKED ISSUE #106: Ensure inside Atomkraft projects for all commands except `init`
Right now, in a lot of places in `Atomkraft`, operations are attempted without ensuring first that the user is inside the Atomkraft project. A couple of examples:

- `atomkraft chain testnet`, when executed outside of a project, attempts to open `chain.toml` (non-present), and as a result throws the exception `FileNotFoundError: [Errno 2] No such file or directory: 'None/chain.toml'`
- `atomkraft reactor --actions a --variables b`, when executed outside of a project, attempts to open `reactors/reactor.py` (non-present), and throws the exception `FileNotFoundError: [Errno 2] No such file or directory: './reactors/reactor.py'

This needs to be fixed. The simplest solution is probably in CLI, before executing anything except `init`, make sure we are inside an Atomkraft project, by executing [project_root()](https://github.com/informalsystems/atomkraft/blob/31b3e35057e48c524dcd88d156a9dd4cdcf15bb4/atomkraft/utils/project.py), which, as described in https://github.com/informalsystems/atomkraft/issues/46#issuecomment-1196526209 should raise an exception if not inside an Atomkraft project.

### PR DESCRIPTION
**Pull request by rnbguy**
Closes #106 

- [ ] Add tests

### CODE REVIEW

**Review by hvanz — APPROVED** [review]
LGTM.

**Review by hvanz — APPROVED** [review]
LGTM.

**Review by andrey-kuprianov — APPROVED** [review]
LGTM! I have improved the error message a bit; @rnbguy please take a look

**Comment by rnbguy** [comment]
@andrey-kuprianov it looks great. :+1: I was gonna add project-specific error classes in later PRs. Because `RuntimeError` can come from anything.

Awesome that you added one already :slightly_smiling_face:

**Pull request merged**
