### PR TITLE
Tutorial updates

### LINKED ISSUE #148: No fees by default
For our testnets, we should have no fees by default since all our models for now are not modelling fees. (Alternatively, we should model fees in the models).
This is important for PR #147 .

### PR DESCRIPTION
**Pull request by ivan-gavran**
- included simulation in the tutorial
- used a more meaningful predicate to illustrate sampling

Merge together with: [Modelator#280](https://github.com/informalsystems/modelator/pull/280)

Remaining issues:
 - [x] Make sure that there are no fees in the execution (since fees are not modelled) : Issue #148 
 
Blocking:
- [ ] Next release of modelator
- [ ] Bump modelator version

### CODE REVIEW

**Comment by rnbguy** [comment]
- broadcast method already takes zero fees by default.
https://github.com/informalsystems/atomkraft/blob/17e859aabf3f058ef1374d2da0565e9f2a45b0e3/atomkraft/chain/testnet.py#L345
- we just need to change the default chain config to zero.
https://github.com/informalsystems/atomkraft/blob/17e859aabf3f058ef1374d2da0565e9f2a45b0e3/template/chain.toml#L10

but wait till we discuss about this.

**Comment by ivan-gavran** [comment]
> * we just need to change the default chain config to zero.
>   https://github.com/informalsystems/atomkraft/blob/17e859aabf3f058ef1374d2da0565e9f2a45b0e3/template/chain.toml#L10

I tried this out, but the same problem persists:
```
root:reactor.py:22 Step: Transfer
INFO     root:reactor.py:36 	Sender:    Alice (cosmos1skjykwsfedmr9x4e3m87qcmlqm93tuypxhudwu)
INFO     root:reactor.py:37 	Receiver:  Bob (cosmos1jsfzp2rre5lug0q76k7raryvc85nfql6pcua5e)
INFO     root:reactor.py:38 	Amount:    100stake
INFO     root:reactor.py:43 Status: Error
INFO     root:reactor.py:44 	code: 5
INFO     root:reactor.py:45 	log:  failed to execute message; message index: 0: 80stake is smaller than 100stake: insufficient funds
```

 I am curious about why it mentions `80stake`: this does not seem to any constants that we've seen in config files.

**Comment by ivan-gavran** [comment]
> I am curious about why it mentions `80stake`: this does not seem to any constants that we've seen in config files.

The `80stake` comes from the fact that [in the reactor](https://github.com/informalsystems/atomkraft/blob/fdd376142f0907fbe4b32981bf47b7b941639def/examples/cosmos-sdk/transfer/reactor.py#L34) we are sending `20stake` for gas.
However, if I try to remove it, I get
```
out of gas in location: ReadFlat; gasWanted: 0, gasUsed: 1000: out of gas
```

Thus, the question is: is there a way to remove any fees (including fees for gas). Or, if it does not make sense, then should we always include gas cost into our models?

**Comment by rnbguy** [comment]
From my previous reply :slightly_smiling_face:

> - we just need to change the default chain config to zero.
> https://github.com/informalsystems/atomkraft/blob/17e859aabf3f058ef1374d2da0565e9f2a45b0e3/template/chain.toml#L10

But the question remains if we want to model gas fees in our specs.

**Comment by ivan-gavran** [comment]
> From my previous reply 🙂
> 
> > * we just need to change the default chain config to zero.
> >   https://github.com/informalsystems/atomkraft/blob/17e859aabf3f058ef1374d2da0565e9f2a45b0e3/template/chain.toml#L10
> 
> But the question remains if we want to model gas fees in our specs.

No, I tried that (in my previous reply :) ) and the same problem persists (so, there must be something else)

**Review by rnbguy — CHANGES_REQUESTED** [review]
Thanks for the PR. Great that you removed the mdx blocks from tutorials.

I added a commit to test out modelator changes in CI. Should be updated with new modelator release before merge.

**Comment by rnbguy** [comment]
@ivan-gavran, the MDX tests are failing. Can you please look into it?

**Pull request closed without merging**
