### PR TITLE
Improve `test` subcommands

### LINKED ISSUE #129: Generate tests for all available traces
Currently `test trace` command only supports one trace per invocation.

For an already setup and trace generated Atomkraft project, `test trace --all` will be a convenient subcommand.

### LINKED ISSUE #130: CLI param for number of tests to generate from a model and a test scenario
Currently, `test model` takes a model and a list of test scenarios to produce one test (from the latest trace) per test scenario.

Atomkraft is supposed to execute on multiple traces - not just the latest trace.

So a `--max-traces` flag should be added to mention the number of traces that Atomkraft will generate and run tests on them.

### PR DESCRIPTION
**Pull request by rnbguy**
Closes #130 
Closes #129

### CODE REVIEW

**Comment by rnbguy** [comment]
Strangely, on my machine, `test model --max-trace <num>` non-deterministically fails on the _second generated test_(in the loop) with the following error,
```
ImportError while importing test module '/home/ranadeep/informal/atomkraft/examples/cosmos-sdk/transfer/transfer/tests/test_transfer_2022_09_05T17_17_33_148/test_Ex_violation2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'test_Ex_violation2'
```
Not sure what's causing it.

**Comment by andrey-kuprianov** [comment]
@rnbguy you are using `--max-traces`; let's probably use single case, i.e. `--max-trace` to be more compatible with the arguments `--max-error`, `--max-run` from Apalache... It doesn't cost us much, but will help the users to avoid confusion...

**Comment by rnbguy** [comment]
I found this paragraph from [`pytest` invocation documentation](https://docs.pytest.org/en/7.1.x/how-to/usage.html).

> Calling pytest.main() will result in importing your tests and any modules that they import. Due to the caching mechanism of python’s import system, making subsequent calls to pytest.main() from the same process will not reflect changes to those files between the calls. For this reason, making multiple calls to pytest.main() from the same process (in order to re-run tests, for example) is not recommended.

My guess is this is the reason. Because I have seen a correlation between the presence of `__pycache__` directory and the raised error.

**Comment by rnbguy** [comment]
The errors are fixed now :slightly_smiling_face:

I group the test files first and then invoke `pytest.main` only once.

**Review by andrey-kuprianov — APPROVED** [review]
Nice Rano! The way you handle additional arguments by passing them to `checker_params` seems to be a good solution for now; later will will think how to do it properly and refactor the interaction between atomkraft an modelator...

I have quickly tested the changes on my machine; it seems to work fine:)

**Pull request merged**
