### PR TITLE
docs(tutorial): update `transfer` tutorial

### LINKED ISSUE #148: No fees by default
For our testnets, we should have no fees by default since all our models for now are not modelling fees. (Alternatively, we should model fees in the models).
This is important for PR #147 .

### PR DESCRIPTION
**Pull request by ivan-gavran**
Closes #148

A rebased version of #147 

- included simulation in the tutorial
- used a more meaningful predicate to illustrate sampling

Merge together with: [Modelator#288](https://github.com/informalsystems/modelator/pull/288)

Remaining issues:
 - [x] Make sure that there are no fees in the execution (since fees are not modelled) : Issue #148 
 
Blocking:
- [ ] Next release of modelator
- [ ] Bump modelator version

### CODE REVIEW

**Comment by ivan-gavran** [comment]
@rnbguy , mdx tests should be timing out because of the issue we discussed on the call, that `atomkraft init` always uses a template from `dev` and not from the current branch. Other than that, I believe this is ready to be merged so I'm asking for your final review

**Comment by rnbguy** [comment]
Thanks :slightly_smiling_face: but this should be fixed before it gets merged. PRs are coming :rocket:

**Comment by rnbguy** [comment]
The timed out CI jobs should be fine when #181 is merged.

**Review by rnbguy — APPROVED** [review]
LGTM

**Pull request merged**
